"""Add TaskStatusChange

Revision ID: 085a8bf4693f
Revises: 0b593a56ccb0
Create Date: 2026-06-22 15:51:21.844772

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "085a8bf4693f"
down_revision: str | Sequence[str] | None = "0b593a56ccb0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_status_changes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "task_status_change_task_id_changed_at_idx",
        "task_status_changes",
        ["task_id", "changed_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("task_status_change_task_id_changed_at_idx", "task_status_changes")
    op.drop_table("task_status_changes")
    # ### end Alembic commands ###
