"""add changed_by column and table Users

Revision ID: b2bfdeb300d6
Revises: 085a8bf4693f
Create Date: 2026-07-06 13:06:28.457867

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from src.infrastructure.db.seed_users import ADMIN_USER_ID, USER_USER_ID

# revision identifiers, used by Alembic.
revision: str = "b2bfdeb300d6"
down_revision: str | Sequence[str] | None = "085a8bf4693f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="role", native_enum=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        sa.table(
            "users",
            sa.column("id", sa.UUID()),
            sa.column("display_name", sa.String()),
            sa.column("role", sa.String()),
        ),
        [
            {"id": ADMIN_USER_ID, "display_name": "Admin", "role": "admin"},
            {"id": USER_USER_ID, "display_name": "User", "role": "user"},
        ],
    )
    op.add_column(
        "task_status_changes", sa.Column("changed_by", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        "task_status_changes_changed_by_fkey",
        "task_status_changes",
        "users",
        ["changed_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "task_status_changes_changed_by_fkey", "task_status_changes", type_="foreignkey"
    )
    op.drop_column("task_status_changes", "changed_by")
    op.drop_table("users")
    # ### end Alembic commands ###
