"""add tasks.created_by

Revision ID: eeefb4498faa
Revises: b2bfdeb300d6
Create Date: 2026-10-08 15:36:31.359715

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeefb4498faa"
down_revision: str | Sequence[str] | None = "b2bfdeb300d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("created_by", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "task_created_by_fkey",
        "tasks",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("task_created_by_fkey", "tasks", type_="foreignkey")
    op.drop_column("tasks", "created_by")
    # ### end Alembic commands ###
